### ISSUE TITLE
feat: Delete wallet & Organization (BE)

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#335]
### Tasks: ###

- [x] Implement API to delete organization
- [x] Implement delete organization data in keycloak 

1. Agent is spun up - Applied validations to check if any connection, ceredential and presentation and wallet is exists against that orgId
2. Agent is not spun up - Applied validations to check if any user or invitation is exists against that orgId
3. If only organization is created and if no data against that orgId, then organization should be deleted directly

- [x] Implement API to delete wallet
- [x] Implement API to delete organization invitations

**Comment by KulkarniShashank** [comment]
Duplicate Issue: https://github.com/credebl/platform/issues/741

**Comment by sayali-chavan96** [comment]
## Pending Todos:

### Backend

- [ ] User should not be able to access the schema and credential definition from a different network

**Comment by GHkrishna** [comment]
Closing as completed
